### ISSUE TITLE
Vsp title: Curious about "Spae of the Wallow"

### ISSUE THREAD

**Issue by jgnewman** [martensas/edda#36]
I think "Spae of the Wallow" sounds really cool so I tried to reverse engineer how you got here from _völuspá_. As far as I can tell, it looks like you've engineered "spae" as a cognate for _spá_ (at least, I'm not aware of this word in Middle/Modern English). However, if you're looking for an English descendant of _*spehōną_, even though we took "spy" from French, it's originally Frankish and does appear to come from that PGmc root.

Wrt to wallow, I'm really curious about this choice. "Wallow" in English means, like, to unrestrainedly indulge in something and, as far as I can tell, I don't think it comes from the same root as _völva_. On the other hand, we do have "wale" which does come from the right root and is preserved in words such as "gunwale". A woman wielding a wale might pretty easily be called a "wale-woman" or even "waless" (although I think -ess is French).

Maybe you have a super cool explanation for "spae of the wallow", but if a lot of that is just theoretical cognate work, maybe you could call it something like "The Spying of the Walewoman"

**Comment by martensas** [comment]
**Spae** is a somewhat rare English word borrowed from Scots. It means prophecy; the goal here is to use cognates, even hypothetical ones, of the native words rather than Greek/Latinate classical terminology. A lot of them sound weird and foreign but that must have went for _prophecy_, _sibyll_ as well at some point. **Wallow** is the phonological cognate of vǫlva from *walwǭ, compare rhyming svǫlva 'swallow' from *swalwǭ. I agree that the semantics of its homophone are unfortunate, but it is what it is.
